### ISSUE TITLE
Bitcoin has been accepted into Unicode

### ISSUE THREAD

**Issue by ghost** [ecogex/bitcoinsymbol-website#39]
Your website, specifically the `FAQ`-section, is out of date (and wrong) because of it. Specially this section:
> As the attempts to add the double vertical dashes B to Unicode has failed, we believe that this is a really long and complicated process.```

No idea when it will be included in a release though, but I feel like the FAQ should be updated to at least reflect this change.

Source: http://www.unicode.org/L2/L2015/15254.htm#145-C7
Original draft (version two IIRC): http://www.unicode.org/L2/L2015/15229-bitcoin-sign.pdf

**Comment by fitojb** [comment]
Indeed. This site’s whole point is now moot since U+20BF, ₿, is available (it’s even included in Segoe UI since Windows 10 Creators Update).

**Comment by Ressettius** [comment]
There is another way, has anyone ever thought of unicode combination characters?
Ex:  B͈̎
